# Generated by Django 2.0 on 2018-12-17 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('fecha_estreno', models.DateField()),
                ('fecha_estreno_video', models.DateField()),
                ('imdb_url', models.CharField(max_length=100)),
                ('categorias', models.ManyToManyField(to='principal.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField()),
                ('fecha', models.DateField()),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Pelicula')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=100)),
                ('ocupacion', models.CharField(max_length=100)),
                ('codigo_postal', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='puntuacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Usuario'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='puntuaciones',
            field=models.ManyToManyField(through='principal.Puntuacion', to='principal.Usuario'),
        ),
    ]
