# Generated by Django 2.0 on 2018-12-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='codigo_postal',
            field=models.CharField(max_length=100),
        ),
    ]
