# Generated by Django 2.0 on 2018-12-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_auto_20181217_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='fecha_estreno_video',
            field=models.DateField(null=True),
        ),
    ]
