# Generated by Django 2.0 on 2018-12-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_auto_20181225_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='fecha_estreno',
            field=models.DateField(null=True),
        ),
    ]
